# Header
menu:
  Home: /
  Archives: /archives

github: https://github.com/yangguang1029
logo_title:
blog_title: 杨光的笔记

# Content
excerpt_link: Read More
fancybox: true
mathjax: false

# Sidebar
sidebar: right
widgets:
- recent_posts
- tag
- archive

# Miscellaneous
wx_block: false
google_analytics:
favicon:
twitter:
google_plus:
fb_admins:
fb_app_id:

baidu_tongji: true

# Duoshuo
duoshuo_shortname:
# >>> Conments 评论系统 <<<
# Chose ONE as your comment system and keep others disable.
# 选一个作为网站评论系统，其他保持禁用。

disqus:
  #on: true
  shortname:
  # https://help.disqus.com/customer/en/portal/articles/466208-what-s-a-shortname-
  # It is unnecessary to enable disqus here if
  # you have set "disqus_shortname" in your site's "_config.yml"

duoshuo:
  #on: true
  domain:
  # 是否开启多说评论，http://duoshuo.com/create-site/
  # 使用上面网址登陆你的多说，然后创建站点，在 domain 中填入你设定的域名
  # http://你的多说域名.duoshuo.com

youyan:
  on: true
  id: 2148209
  # 是否开启友言评论，http://www.uyan.cc/index.php
  # id 中填写你的友言用户数字ID，注册后进入后台管理即可查看
  # 友言服务在 Web 环境下运行，普通本地环境无法查看，请部署后在线上测试。

# >>> <<<

# Swiftype Search
swiftype_key:
